http:
  port: ${PORT_API}
admin:
  port: 9876
  hostname: 0.0.0.0

####### API ENDPOINTS DEFINITION ########

####### GATEWAY CUSTOM ENDPOINT ########
apiEndpoints:  
  gatewayCustomApi:
    - host: '*'
      paths: ['/users/*']
      methods: ['DELETE']
      scopes: ['users:remove']

####### ACTIVITY ENDPOINT ########
  activityApi:
    - host: '*'
      paths: ['/users/*/activities', '/users/*/activities/*']
      methods: ["GET"]
      scopes: ['activities:read']

    - host: '*'
      paths: ['/users/*/activities']
      methods: ["POST"]
      scopes: ['activities:register']

    - host: '*'
      paths: ['/users/*/activities/*']
      methods: ["DELETE"]
      scopes: ['activities:remove']

####### ACCOUNT ENDPOINT ########  
  accountPublicApi:
    - host: '*'
      paths: ['/users']
      methods: ['POST']

    - host: '*'
      paths: ['/users/auth']
      methods: ['POST']
  
  accountPrivateApi:     
    - host: '*'
      paths: ['/users']
      methods: ['GET']
      scopes: ['users:readAll']

    - host: '*'
      paths: ['/users/*']
      methods: ['GET']
      scopes: ['users:read']

    - host: '*'
      paths: ['/users/*']
      methods: ['PUT']
      scopes: ['users:update']  

####### SERVICE ENDPOINTS DEFINITIONS ########
serviceEndpoints:
  accountService:
    url: '${ACCOUNT_SERVICE}'
  activityService:
    url: '${ACTIVITY_SERVICE}'
  gatewayService:
    url: '${API_GATEWAY_SERVICE}'

####### POLICIES USED IN PIPELINES DEFINITION ########
policies:
  - log
  - proxy
  - rate-limit
  - ocariot-jwtScopes-policy
  - ocariot-jwt-policy
  - ocariot-auth-policy
  - ocariot-body-parser-policy

####### PIPELINES DEFINITION ########
#### Pipeline no manage data coming from ACCOUNT PRIVATE and PUBLIC APIs ####
pipelines: 
  accountPublicPipeline:
    apiEndpoints: ['accountPublicApi']
    policies:
      - ocariot-auth-policy:
        - 
          condition:
            name: 'is-auth'
            authpath: '/users/auth'
          action:
            urlauthservice: ${ACCOUNT_SERVICE}/users/auth
            secretOrPublicKey: ${SECRET_JWT}
            issuer: ${ISSUER}
      - proxy:
          - action:
              prependPath:  true
              ignorePath:   false
              stripPath:    false
              changeOrigin: true
              serviceEndpoint: accountService

  accountPrivatePipeline:
    apiEndpoints: ['accountPrivateApi']
    policies:
      - ocariot-jwt-policy:
          - action:
              secretOrPublicKey: ${SECRET_JWT}
              issuer: ${ISSUER}
      - ocariot-jwtScopes-policy:
      - proxy:
          - action:
              prependPath:  true
              ignorePath:   false
              stripPath:    false
              changeOrigin: true
              serviceEndpoint: accountService

  #### Pipeline no manage data coming at ACTIVITY API ####
  activityPipeline:
    apiEndpoints: ['activityApi']
    policies:
      - ocariot-jwt-policy:
          - action:
              secretOrPublicKey: ${SECRET_JWT}
              issuer: ${ISSUER}
      - ocariot-jwtScopes-policy:
      - proxy:
          - action:
              prependPath:  true
              ignorePath:   false
              stripPath:    false
              changeOrigin: true
              serviceEndpoint: activityService

  gatewayPipeline:
    apiEndpoints: ['gatewayCustomApi']
    policies:
      - ocariot-jwt-policy:
          - action:
              secretOrPublicKey: ${SECRET_JWT}
              issuer: ${ISSUER}
      - ocariot-jwtScopes-policy:
      - proxy:
          - action:
              prependPath:  true
              ignorePath:   false
              stripPath:    false
              changeOrigin: true
              serviceEndpoint: gatewayService