http:
  port: 8080
admin:
  port: 9876
  hostname: localhost
apiEndpoints:
  api:
    host: localhost
    paths: '/ip'
    scopes: 
      - 'admin'
      - 'educator'
      - 'family'
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
  - ocariot-jwtScopes-policy
  - ocariot-jwt-policy
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
      - ocariot-jwt-policy:
          - action:
              secretOrPublicKey: 12345
              issuer: 'ocariot'
      - ocariot-jwtScopes-policy:
      - proxy:
          - action:
              serviceEndpoint: httpbin
              changeOrigin: true