http:
  port: 8080
admin:
  port: 9876
  hostname: localhost
apiEndpoints:
  api:
    host: localhost
    paths: '/ip'
    scopes:
      - 'admin'
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
  - authorization
  - authentication
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
      # - authentication:
      #     action:
      #       secretOrPublicKey: 12345
      #       issuer: 'ocariot'
      - authorization:
          action:
      - proxy:
          - action:
              serviceEndpoint: httpbin
              changeOrigin: true