http:
  port: ${PORT_API}
admin:
  port: 9876
  hostname: 0.0.0.0

####### API ENDPOINTS DEFINITION ########

####### GATEWAY CUSTOM ENDPOINT ########
apiEndpoints:  
  gatewayCustomApi:
    - host: '*'
      paths: ['/users/:user_id']
      methods: ['DELETE']
      scopes: ['users:remove']

####### ACCOUNT ENDPOINT ########  
  accountPublicApi:
    - host: 'localhost'
      paths: ['/users']
      methods: ['POST']

    - host: '*'
      paths: ['/users/auth']
      methods: ['POST']
  
  accountPrivateApi:     
    - host: '*'
      paths: ['/users']
      methods: ['GET']
      scopes: ['users:readAll']

    - host: '*'
      paths: ['/users/:user_id']
      methods: ['GET']
      scopes: ['users:read']

    - host: '*'
      paths: ['/users/:user_id']
      methods: ['PATCH']
      scopes: ['users:update'] 

####### ACTIVITY ENDPOINT ########
  activityPrivateApi:
    - host: '*'
      paths: ['/activities']
      methods: ["GET"]
      scopes: ['activities:readAll']

    - host: '*'
      paths: ['/users/:user_id/activities', '/users/:user_id/activities/*']
      methods: ["GET"]
      scopes: ['activities:read']

    - host: '*'
      paths: ['/users/:user_id/activities']
      methods: ["POST"]
      scopes: ['activities:register']

    - host: '*'
      paths: ['/users/:user_id/activities/:activity_id']
      methods: ["PATCH"]
      scopes: ['activities:update']

    - host: '*'
      paths: ['/users/:user_id/activities/:activity_id']
      methods: ["DELETE"]
      scopes: ['activities:remove']

    - host: '*'
      paths: ['/sleep']
      methods: ["GET"]
      scopes: ['sleep:readAll']

    - host: '*'
      paths: ['/users/:user_id/sleep', '/users/:user_id/sleep/:sleep_id']
      methods: ["GET"]
      scopes: ['sleep:read']

    - host: '*'
      paths: ['/users/:user_id/sleep']
      methods: ["POST"]
      scopes: ['sleep:register']

    - host: '*'
      paths: ['/users/:user_id/sleep/:sleep_id']
      methods: ["PATCH"]
      scopes: ['sleep:update']

    - host: '*'
      paths: ['/users/:user_id/sleep/:sleep_id']
      methods: ["DELETE"]
      scopes: ['sleep:remove']

#   ENVIRONMENTAL ACTIVITY
  activityPublicApi:
    - host: '*'
      paths: ['/environments']
      methods: ["GET"]

    - host: '*'
      paths: ['/environments']
      methods: ["POST"]

    - host: '*'
      paths: ['/environments/:environment_id']
      methods: ["DELETE"]
 

####### SERVICE ENDPOINTS DEFINITIONS ########
serviceEndpoints:
  accountService:
    url: '${ACCOUNT_SERVICE}'
  activityService:
    url: '${ACTIVITY_SERVICE}'
  gatewayService:
    url: '${API_GATEWAY_SERVICE}'

####### POLICIES USED IN PIPELINES DEFINITION ########
policies:
  - log
  - proxy
  - rate-limit
  - ocariot-jwtScopes-policy
  - ocariot-jwt-policy
  - ocariot-auth-policy
  - ocariot-body-parser-policy

####### PIPELINES DEFINITION ########
#### Pipeline no manage data coming from ACCOUNT PRIVATE and PUBLIC APIs ####
pipelines: 
  accountPublicPipeline:
    apiEndpoints: ['accountPublicApi']
    policies:
      - ocariot-body-parser-policy: 
      - ocariot-auth-policy:
        - 
          condition:
            name: 'is-auth'
            authpath: '/users/auth'
          action:
            urlauthservice: ${ACCOUNT_SERVICE}/users/auth
            secretOrPublicKey: ${SECRET_JWT}
            issuer: ${ISSUER}
      - proxy:
          - action:
              prependPath:  true
              ignorePath:   false
              stripPath:    false
              changeOrigin: true
              serviceEndpoint: accountService


  accountPrivatePipeline:
    apiEndpoints: ['accountPrivateApi']
    policies:
      - ocariot-body-parser-policy: 
      - ocariot-jwt-policy:
          - action:
              secretOrPublicKey: ${SECRET_JWT}
              issuer: ${ISSUER}
      - ocariot-jwtScopes-policy:
      - proxy:
          - action:
              prependPath:  true
              ignorePath:   false
              stripPath:    false
              changeOrigin: true
              serviceEndpoint: accountService


 #### Pipelines to manage data coming from ACTIVITY PRIVATE and PUBLIC APIs ####
  activityPrivatePipeline:
    apiEndpoints: ['activityPrivateApi']
    policies:
      - ocariot-body-parser-policy: 
      - ocariot-jwt-policy:
          - action:
              secretOrPublicKey: ${SECRET_JWT}
              issuer: ${ISSUER}
      - ocariot-jwtScopes-policy:
      - proxy:
          - action:
              prependPath:  true
              ignorePath:   false
              stripPath:    false
              changeOrigin: true
              serviceEndpoint: activityService

  
  activityPublicPipeline:
    apiEndpoints: ['activityPublicApi']
    policies:
      - ocariot-body-parser-policy: 
      - proxy:
          - action:
              prependPath:  true
              ignorePath:   false
              stripPath:    false
              changeOrigin: true
              serviceEndpoint: activityService


#### Pipelines to manage data coming from GATEWAY CUSTOM APIs ####
  gatewayPipeline:
    apiEndpoints: ['gatewayCustomApi']
    policies:
      - ocariot-body-parser-policy: 
      - ocariot-jwt-policy:
          - action:
              secretOrPublicKey: ${SECRET_JWT}
              issuer: ${ISSUER}
      - ocariot-jwtScopes-policy:
      - proxy:
          - action:
              prependPath:  true
              ignorePath:   false
              stripPath:    false
              changeOrigin: true
              serviceEndpoint: gatewayService
